### ISSUE TITLE
Error when running app

### ISSUE THREAD

**Issue by itsdani121** [evilrat/flutter_zoom_sdk#28]
when i run app after passing meeting id or password then app crashed and show this issue 

       

```
/Gralloc3(10769): allocator 3.x is not supported
I/HiTouch_HiTouchSensor(10769): HiTouch restricted: Sub windows restricted.
D/HiTouch_PressGestureDetector(10769): onAttached, package=com.wasisoft.wsms, windowType=2030, mHiTouchRestricted=true
D/mali_winsys(10769): EGLint new_window_surface(egl_winsys_display *, void *, EGLSurface, EGLConfig, egl_winsys_surface **, EGLBoolean) returns 0x3000
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687678): avc: granted { read } for pid=10769 name="logs" dev="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24
,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687679): avc: granted { read open } for pid=10769 path="/storage/emulated/0/Android/data/com.wasisoft.wsms/logs" dev
="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687680): avc: granted { read } for pid=10769 name="logs" dev="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24
,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687681): avc: granted { read open } for pid=10769 path="/storage/emulated/0/Android/data/com.wasisoft.wsms/logs" dev
="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687684): avc: granted { read } for pid=10769 name="logs" dev="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24
,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687685): avc: granted { read open } for pid=10769 path="/storage/emulated/0/Android/data/com.wasisoft.wsms/logs" dev
="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
W/m.wasisoft.wsms(10769): type=1400 audit(0.0:1687686): avc: granted { read } for pid=10769 name="logs" dev="sdcardfs" ino=307714 scontext=u:r:untrusted_app:s0:c24
,c259,c512,c768 tcontext=u:object_r:sdcardfs:s0 tclass=dir
V/AudioManager(10769): isWiredHeadsetOn...
V/AudioManager(10769): isBluetoothA2dpOn...
V/AudioManager(10769): isBluetoothScoOn...
W/ActivityThread(10769): handleWindowVisibility: no activity for token android.os.BinderProxy@d4a5415
V/ActivityThread(10769): callActivityOnCreate
D/ActivityThread(10769): add activity client record, r= ActivityRecord{796dce7 token=android.os.BinderProxy@d4a5415 {com.wasisoft.wsms/com.zipow.videobox.JoinByURL
Activity}} token= android.os.BinderProxy@d4a5415
I/Camera  (10769): open camera: 0, package name: com.wasisoft.wsms
I/HwCameraUtil(10769): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = true
I/Camera  (10769): close camera: 0, package name: com.wasisoft.wsms
I/HwCameraUtil(10769): notifySurfaceFlingerCameraStatus : isFront = false , isOpend = false
I/Camera  (10769): open camera: 1, package name: com.wasisoft.wsms
I/HwCameraUtil(10769): notifySurfaceFlingerCameraStatus : isFront = true , isOpend = true
I/HwCameraUtil(10769): notifySurfaceFlingerFrontCameraStatus 8011 transact success!
I/Camera  (10769): close camera: 1, package name: com.wasisoft.wsms
I/HwCameraUtil(10769): notifySurfaceFlingerCameraStatus : isFront = true , isOpend = false
I/HwCameraUtil(10769): notifySurfaceFlingerFrontCameraStatus 8012 transact success!
D/SensorManager(10769): 0x70c900d370 addFd fd=180
I/Choreographer(10769): Skipped 96 frames!  The application may be doing too much work on its main thread.
D/HwGalleryCacheManagerImpl(10769): mIsEffect:false
D/BitmapFactory(10769): sampleSize 1, isHardware 0, isMutable 0, prefColorType 4, requireUnpremultiplied 0
D/skia    (10769): --- Failed to create image decoder with message 'unimplemented'
W/ActivityThread(10769): handleWindowVisibility: no activity for token android.os.BinderProxy@351ab6
V/ActivityThread(10769): callActivityOnCreate
D/AndroidRuntime(10769): Shutting down VM
I/QarthLog(10769): [PatchStore] createDisableExceptionQarthFile
I/QarthLog(10769): [PatchStore] create disable file for com.wasisoft.wsms uid is 10792
E/AndroidRuntime(10769): FATAL EXCEPTION: main
E/AndroidRuntime(10769): Process: com.wasisoft.wsms, PID: 10769
E/AndroidRuntime(10769): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wasisoft.wsms/com.zipow.videobox.ConfActivityNormal}: android.view.
InflateException: Binary XML file line #28 in com.wasisoft.wsms:layout/zm_conf_main_screen: Binary XML file line #7 in com.wasisoft.wsms:layout/zm_panel_float_btn:
Error inflating class com.google.android.flexbox.FlexboxLayout
E/AndroidRuntime(10769):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3782)
E/AndroidRuntime(10769):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
E/AndroidRuntime(10769):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
E/AndroidRuntime(10769):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(10769):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(10769):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
E/AndroidRuntime(10769):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(10769):        at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(10769):        at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(10769):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10769):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(10769):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(10769): Caused by: android.view.InflateException: Binary XML file line #28 in com.wasisoft.wsms:layout/zm_conf_main_screen: Binary XML file line #
7 in com.wasisoft.wsms:layout/zm_panel_float_btn: Error inflating class com.google.android.flexbox.FlexboxLayout
E/AndroidRuntime(10769): Caused by: android.view.InflateException: Binary XML file line #7 in com.wasisoft.wsms:layout/zm_panel_float_btn: Error inflating class co
m.google.android.flexbox.FlexboxLayout
E/AndroidRuntime(10769): Caused by: java.lang.ClassNotFoundException: com.google.android.flexbox.FlexboxLayout
E/AndroidRuntime(10769):        at java.lang.Class.classForName(Native Method)
E/AndroidRuntime(10769):        at java.lang.Class.forName(Class.java:454)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.createView(LayoutInflater.java:825)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1016)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1243)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.parseInclude(LayoutInflater.java:1273)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1129)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:1136)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1094)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.inflate(LayoutInflater.java:692)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.inflate(LayoutInflater.java:536)
E/AndroidRuntime(10769):        at android.view.LayoutInflater.inflate(LayoutInflater.java:483)
E/AndroidRuntime(10769):        at com.android.internal.policy.PhoneWindow.setContentView(PhoneWindow.java:520)
E/AndroidRuntime(10769):        at com.android.internal.policy.HwPhoneWindow.setContentView(HwPhoneWindow.java:328)
E/AndroidRuntime(10769):        at android.app.Activity.setContentView(Activity.java:3459)
E/AndroidRuntime(10769):        at androidx.activity.ComponentActivity.setContentView(ComponentActivity.java:403)
E/AndroidRuntime(10769):        at com.zipow.videobox.ConfActivityNormal.onCreate(ConfActivityNormal.java:624)
E/AndroidRuntime(10769):        at android.app.Activity.performCreate(Activity.java:8086)
E/AndroidRuntime(10769):        at android.app.Activity.performCreate(Activity.java:8074)
E/AndroidRuntime(10769):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1313)
E/AndroidRuntime(10769):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3755)
E/AndroidRuntime(10769):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3961)
E/AndroidRuntime(10769):        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
E/AndroidRuntime(10769):        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
E/AndroidRuntime(10769):        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
E/AndroidRuntime(10769):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2386)
E/AndroidRuntime(10769):        at android.os.Handler.dispatchMessage(Handler.java:107)
E/AndroidRuntime(10769):        at android.os.Looper.loop(Looper.java:213)
E/AndroidRuntime(10769):        at android.app.ActivityThread.main(ActivityThread.java:8178)
E/AndroidRuntime(10769):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(10769):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(10769):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1101)
E/AndroidRuntime(10769): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.flexbox.FlexboxLayout" on path: DexPathList[[zip file "
/data/app/com.wasisoft.wsms-Na2XBSqBZ24Ysw7o8ohcFA==/base.apk"],nativeLibraryDirectories=[/data/app/com.wasisoft.wsms-Na2XBSqBZ24Ysw7o8ohcFA==/lib/arm64, /data/app
/com.wasisoft.wsms-Na2XBSqBZ24Ysw7o8ohcFA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64, /hw_product/lib64, /system/product/lib64]]
E/AndroidRuntime(10769):        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
E/AndroidRuntime(10769):        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
E/AndroidRuntime(10769):        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
E/AndroidRuntime(10769):        ... 39 more
I/Process (10769): Sending signal. PID: 10769 SIG: 9
Lost connection to device.

```

i dont know why it give error before it working fine my package is 0.0.6 and flutter doctor is 
```

C:\Users\WasiSoft\AndroidStudioProjects\wsms>flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.5.3, on Microsoft Windows [Version 10.0.19041.508], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[√] Chrome - develop for the web
[√] Android Studio (version 2020.3)
[√] Connected device (3 available)

• No issues found!

```

**Comment by lovishhamal** [comment]
Add this to application tag -> android:name="io.flutter.app.FlutterApplication" in AndroidManifest.xml

and this to proguard-rules.pro

-keep class us.zoom.** { *; }
-keep class com.zipow.** { *; }
-keep class us.zipow.** { *; }
-keep class org.webrtc.** { *; }
-keep class us.google.protobuf.** { *; }
-keep class com.google.crypto.tink.** { *; }
-keep class androidx.security.crypto.** { *; }

in app/gradle 

   buildTypes {
        release {
            minifyEnabled true
            useProguard true
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
