### ISSUE TITLE
App Crash on Android Target SDK 31

### ISSUE THREAD

**Issue by Manojdaiya1992** [evilrat/flutter_zoom_sdk#95]
This is my AndroidManifest.xml file under flutter_zoom_sdk/android/src/main

<application>
    <activity android:name=".CustomWaitActivity" android:exported="false">
        <intent-filter>
            <action android:name="com.evilratt.flutter_zoom_sdk.intent.action.JoinBeforeHost" />
            <category android:name="android.intent.category.DEFAULT"/>
        </intent-filter>
    </activity>
</application>
But I still got the error when I run it on android 31 SDK getting the below error. Please help.
I also tried with android:exported="true" but got the same error

Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(13075): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(13075): at android.app.ActivityThread.handleCreateService(ActivityThread.java:4500)
E/AndroidRuntime(13075): at android.app.ActivityThread.access$1700(ActivityThread.java:247)
E/AndroidRuntime(13075): at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2072)
E/AndroidRuntime(13075): at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(13075): at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(13075): at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(13075): at android.app.ActivityThread.main(ActivityThread.java:7839)
E/AndroidRuntime(13075): at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(13075): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(13075): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
E/AndroidRuntime(13075): Caused by: java.lang.IllegalArgumentException: com.nrichlearning.nrichmobile: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/AndroidRuntime(13075): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/AndroidRuntime(13075): at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/AndroidRuntime(13075): at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
E/AndroidRuntime(13075): at android.app.PendingIntent.getActivity(PendingIntent.java:444)
E/AndroidRuntime(13075): at android.app.PendingIntent.getActivity(PendingIntent.java:408)
E/AndroidRuntime(13075): at us.zoom.sdk.SDKNotificationMgr.showConfNotificationForSDK(SDKNotificationMgr.java:10)
E/AndroidRuntime(13075): at com.zipow.videobox.share.ScreenShareServiceForSDK.onCreate(ScreenShareServiceForSDK.java:3)
E/AndroidRuntime(13075): at android.app.ActivityThread.handleCreateService(ActivityThread.java:4487)

**Comment by ark-brighthustle** [comment]
Workin on fix

**Comment by Manojdaiya1992** [comment]
Any idea of release

**Comment by ghost** [comment]
@evilrat ....any updates on the end date?

**Comment by vishnu-vr** [comment]
@evilrat could you please let us know the status?
